const personData = [
    {
        id: 1,
        color: "",
        person: "Exyl",
        desc: "The supreme leader (Owner of Flute Gang)",
        special: "rainbow",
    },{
        id: 2,
        color: "",
        person: "Dalux",
        desc: "The Co-Owner of flute gang with a very nice logo",
        special: "dalux",
    },{
        id: 3,
        color: "",
        person: "Dr.J",
        desc: "BAN",
        special: "mod",
    },{
        id: 4,
        color: "",
        person: "Nebular",
        desc: "You better not ping him.",
        special: "mod",
    },{
        id: 5,
        color: "",
        person: "Russian Spy",
        desc: "He does not talk much, but he is always watching.",
        special: "mod",
    },{
        id: 6,
        color: "",
        person: "Sabba7h",
        desc: "The first mod to be selected after the mod applications",
        special: "mod",
    },{
        id: 7,
        color: "",
        person: "Megan",
        desc: "Aparently watches the chat the whole day",
        special: "mod",
    },{
        id: 8,
        color: "",
        person: "Omatsu",
        desc: "One of the 3 mods that applied and got selected",
        special: "mod",
    },{
        id: 9,
        color: "",
        person: "Alex",
        desc: "One of the 3 mods that applied and got selected",
        special: "mod",
    },{
        id: 10,
        color: "",
        person: "Marci",
        desc: "The Nurse!",
        special: "mod",
    },{
        id: 11,
        color: "",
        person: "MRT",
        desc: "Head Staff in the Geometry Dash server",
        special: "mod",
    },{
        id: 12,
        color: "",
        person: "Tet",
        desc: "Tet, just tet.",
        special: "mod",
    },{
        id: 13,
        color: "",
        person: "blackout",
        desc: "the one that made this website(and is a trap aparently)",
        special: "blackout",
    },{
        id: 14,
        color: "#fff300",
        person: "Nick",
        desc: "The undefeated debate chamption of Flute Gang",
        special: "",
    },{
        id: 15,
        color: "#ff96cb",
        person: "Stringy",
        desc: "↓One of Flute Gang's best coders.",
        special: "",
    },{
        id: 16,
        color: "#fa61ff",
        person: "Twinimi",
        desc: "↑The blender project",
        special: "",
    },{
        id: 17,
        color: "#ffb65c",
        person: "Dodge",
        desc: "60k messages, damn.",
        special: "",
    },{
        id: 18,
        color: "#9c4d84",
        person: "Ganoosh",
        desc: "Another amazing coder in Flute Gang",
        special: "",
    },{
        id: 19,
        color: "#4287f5",
        person: "Yamm",
        desc: "According to nellie and kat he looks like JB",
        special: "",
    },{
        id: 20,
        color: "#c7c7c7",
        person: "Luna",
        desc: "Physics homework.",
        special: "",
    },{
        id: 21,
        color: "#95eb34",
        person: "H4",
        desc: "Genshin Impact sweat",
        special: "",
    },{
        id: 22,
        color: "#9342f5",
        person: "Kat",
        desc: "Gets songs stuck in people's heads",
        special: "",
    },{
        id: 23,
        color: "#a39600",
        person: "Nellie",
        desc: "Falls asleep to people's voices.",
        special: "",
    },{
        id: 24,
        color: "#42f575",
        person: "(  -  - )",
        desc: "Face man",
        special: "",
    },{
        id: 25,
        color: "#a3004f",
        person: "Yasi",
        desc: "HYASI-KUN!!!!!!!!!!",
        special: "",
    },{
        id: 26,
        color: "#fc9dd3",
        person: "Sugar",
        desc: "Drew Dalux Chan, Exyl Chan, Stringy Chan, and Nebular Chan",
        special: "",
    },{
        id: 27,
        color: "#b50015",
        person: "Nasaka",
        desc: "MC Speedrunner + Bewars PRO",
        special: "",
    },{
        id: 28,
        color: "#7f02b5",
        person: "WildCat",
        desc: "The name says it all",
        special: "",
    },{
        id: 29,
        color: "#91f4ff",
        person: "IcyJackie",
        desc: "Loves reacting to people's messages.",
        special: "",
    },{
        id: 30,
        color: "#ff0000",
        person: "Keet",
        desc: "A loyal Abelton cult follower",
        special: "",
    },{
        id: 31,
        color: "#876952",
        person: "ThePerfectAfro",
        desc: "Does he actually have 'ThePerfectAfro'?",
        special: "",
    },{
        id: 32,
        color: "#e31053",
        person: "Rose",
        desc: "The uncle of the server",
        special: "",
    },{
        id: 33,
        color: "#ff963b",
        person: "Senko",
        desc: "Senko. Emojis.",
        special: "",
    },{
        id: 34,
        color: "#ffd7b5",
        person: "Jello",
        desc: "",
        special: "",
    },{
        id: 35,
        color: "#4f49a3",
        person: "Octav",
        desc: "30k messages, Damn",
        special: "",
    },{
        id: 36,
        color: "#a9a4eb",
        person: "Sword",
        desc: "Geometry dash is his thing.",
        special: "",
    },{
        id: 37,
        color: "#ff3045",
        person: "T!K",
        desc: "His actual name is TIKTOK",
        special: "",
    },{
        id: 38,
        color: "#d524f0",
        person: "Kaneki",
        desc: "You should hear his loli voice",
        special: "",
    },{
        id: 39,
        color: "#f0ba24",
        person: "KoolKat",
        desc: "Default scratch sprite.",
        special: "",
    },{
        id: 40,
        color: "#578f8f",
        person: "Marr",
        desc: "The dude that had the Fortnite pfp",
        special: "",
    },{
        id: 41,
        color: "#1b1e45",
        person: "CarbonDioxide",
        desc: "Spongebob Squarepants",
        special: "",
    },{
        id: 42,
        color: "#3AF3FF",
        person: "Electraboss",
        desc: "Batch and python programmer, made a discord clone in batch called BatchCord",
        special: "",
    }

]
export default personData

/*
{
        id: ,
        color: "",
        person: "",
        desc: "",
        special: "",
    }
*/